#!/bin/bash

RSYNC=$(which rsync)

if [ $# -lt 2 ]; then
    echo "Usage: $(basename $0) <src-dir> <dst-dir>"
    exit 1
fi

SRC_DIR=$1
DST_DIR=$2

${RSYNC} -avz ${SRC_DIR} ${DST_DIR} \
    --exclude vendor \
    --exclude node_modules \
    --exclude cmake-build-debug \
    --exclude .venv \
    --exclude __pycache__\
    --exclude cache \
    --exclude subtree-cache \
    --delete --delete-excluded

