#!/bin/bash

GS=$(which gs)

if [ $# -lt 1 ]; then
    echo "Usage: $(basename $0) <input-file> [<output-file>] [<resolution>]"
    echo "Lighten PDF file with GhostScript."
    exit 1
fi

INPUT_FILE=$1

OUTPUT_FILE=${2:-output.pdf}
RESOLUTION=${3:-130}

${GS} -q -dNOPAUSE -dBATCH -dSAFER \
    -sDEVICE=pdfwrite \
    -dCompatibilityLevel=1.3 \
    -dPDFSETTINGS=/screen \
    -dEmbedAllFonts=true -dSubsetFonts=true \
    -dColorImageDownsampleType=/Bicubic \
    -dColorImageResolution=${RESOLUTION} \
    -dGrayImageDownsampleType=/Bicubic \
    -dGrayImageResolution=${RESOLUTION} \
    -dMonoImageDownsampleType=/Bicubic \
    -dMonoImageResolution=${RESOLUTION} \
    -sOutputFile="${OUTPUT_FILE}" \
    "${INPUT_FILE}"

